name: 'build'

on:
  push:
    branches: 
      - master
      - feature/*
      - hotfix/*
    tags:
      - linux-msft-wsl-*
  pull_request: {}
  workflow_call: {}
  workflow_dispatch: {}

env:
  KERNEL_VERSION: 6.1.21.2

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-build-${{ env.KERNEL_VERSION }}-${{ hashFiles('config-wsl') }}-${{ github.sha }}
          path: |
            ./linux-msft-wsl-${{ env.KERNEL_VERSION }}.tar.gz
            ./**/*.o
            ./**/*.a
            !./linux-msft-wsl-${{ env.KERNEL_VERSION }}/tools/bpf
          restore-keys: |
            ${{ runner.os }}-build-${{ env.KERNEL_VERSION }}-${{ hashFiles('config-wsl') }}-
            ${{ runner.os }}-build-${{ env.KERNEL_VERSION }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Build Kernel
        run: |
          sudo apt-get update -yqq
          sudo bash build-kernel ${{ env.KERNEL_VERSION }}
      - name: Upload Kernel
        uses: actions/upload-artifact@v4
        with:
          name: bzImage
          path: linux-msft-wsl-${{ env.KERNEL_VERSION }}/arch/x86/boot/bzImage
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: bzImage
