name: 'build'

on:
  push:
    branches: 
      - master
      - feature/*
      - hotfix/*
    tags:
      - linux-msft-wsl-*
  pull_request: {}
  workflow_call: {}
  workflow_dispatch: {}

env:
  KERNEL_VERSION: 6.1.21.2

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Install apt packages
        run: |
          sudo apt update
          sudo apt install -y build-essential flex bison dwarves libssl-dev libelf-dev zstd
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          max-size: "800MB"
          key: ${{ runner.os }}-build-${{ env.KERNEL_VERSION }}-${{ hashFiles('config-wsl') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.KERNEL_VERSION }}-${{ hashFiles('config-wsl') }}-
            ${{ runner.os }}-build-${{ env.KERNEL_VERSION }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Build Kernel
        run: bash build-kernel ${{ env.KERNEL_VERSION }}
      - name: Upload Kernel
        uses: actions/upload-artifact@v4
        with:
          name: bzImage
          path: linux-msft-wsl-${{ env.KERNEL_VERSION }}/arch/x86/boot/bzImage
          compression-level: 0
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: bzImage
